# This is a basic workflow to help you get started with Actions

name: Actions_Playground
###################################################################
# Environment Variables                                           #
###################################################################
env:
  AZURE_WEBAPP_NAME: 'dabu-PartsUnlimited'
  LOAD_TEST_CONFIG_FILE: "PartsUnlimited-aspnet45/test/PartsUnlimited.LoadTests/dabu-PartsUnlimitedLoadTest"
  LOAD_TEST_RESOURCE: "dabu-PartsUnlimited"
  Azure_Resource_Group: dabu-PartsUnlimited

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
###################################################################
# QA Stage                                                #
###################################################################
  QA:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Azure login"
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: ${{ env.LOAD_TEST_CONFIG_FILE }}-QA.yaml
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.Azure_Resource_Group }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}-QA.azurewebsites.net"
              }
            ]          
      
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults-QA
          path: ${{ github.workspace }}/loadTest
          
      - name: Azure logout
        if: ${{steps.CacheARMTemplateCI.outputs.cache-hit==false}}
        run: |
          az logout

###################################################################
# Production Stage                                                #
###################################################################
  Production:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Azure login"
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: ${{ env.LOAD_TEST_CONFIG_FILE }}.yaml
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.Azure_Resource_Group }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]          
      
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
          
      - name: Azure logout
        if: ${{steps.CacheARMTemplateCI.outputs.cache-hit==false}}
        run: |
          az logout
